export default [
  {
    _id: '61edffe519594d91f1d2d6bb',
    path: [],
    parent: null,
    ownerId: '61e607f0311d699fd35f509e',
    title: 'The Andy Promise',
    description:
      'On the night of February 2nd 2010 I infiltrated into McDonalds head quarters to get my hands on the secret formula. After months of planning the perfect heist I successfully retrieved the recipe. But McDonalds is now after me so I will release it to the public!',
    ingredients: [
      {
        ingredient: 'Sesame seed buns',
        amount: '1.5',
        unitOfMeasure: '',
        _id: '61edffe519594d91f1d2d6bc',
      },
      {
        ingredient: 'Ground beef',
        amount: '1/4',
        unitOfMeasure: 'lbs',
        _id: '61edffe519594d91f1d2d6bd',
      },
      {
        ingredient: 'Salt',
        amount: '2',
        unitOfMeasure: 'pinches',
        _id: '61edffe519594d91f1d2d6be',
      },
      {
        ingredient: 'Ground black pepper',
        amount: '2',
        unitOfMeasure: 'pinches',
        _id: '61edffe519594d91f1d2d6bf',
      },
      {
        ingredient: 'finely diced onions',
        amount: '1',
        unitOfMeasure: 'teaspoon',
        _id: '61edffe519594d91f1d2d6c0',
      },
      {
        ingredient: 'chopped iceberg lettuce',
        amount: '1/2',
        unitOfMeasure: 'cup',
        _id: '61edffe519594d91f1d2d6c1',
      },
      {
        ingredient: 'dill pickle',
        amount: '2-3',
        unitOfMeasure: 'slices',
        _id: '61edffe519594d91f1d2d6c2',
      },
      {
        ingredient: 'thousand island/special sauce',
        amount: '1',
        unitOfMeasure: 'tablespoon',
        _id: '61edffe519594d91f1d2d6c3',
      },
    ],
    instructions:
<<<<<<< HEAD
      '1. With a serrated knife cut the top off the extra bun half, leaving about a 3/4-inch-thick slice. This will be the middle bun of your sandwich\n\n2. Place the three buns on a hot pan or griddle, face down, and toast them to a light brown. Set aside, but keep the pan hot.\n\n3. Divide the ground beef in half and form it into two thin patties slightly larger than the bun.\n\n4. Cook the patties in the hot pan over medium heat for 1 to 2 minutes on each side. Salt and pepper lightly.\n\n5. Build the burger in the following stacking order from the bottom up:\n\nbottom bun -> special sauce -> onions -> lettuce -> american cheese -> beef patty -> middle bun -> special sauce -> onion -> lettuce -> pickles -> beef patty -> top bun\n\nOptional if you want more than just thousand island dressing make the following sauce:\n\n1/2 cup mayonnaise\n\n2 tablespoons french dressing\n\n4 teaspoons sweet pickle relish\n\n1 tablespoon finely minced white onion\n\n1 teaspoon granulated sugar\n\n1/8 teaspoon salt',
    photo: '',
=======
      '1. With a serrated knife cut the top off the extra bun half, leaving about a 3/4-inch-thick slice. This will be the middle bun of your sandwich\n2. Place the three buns on a hot pan or griddle, face down, and toast them to a light brown. Set aside, but keep the pan hot.\n3. Divide the ground beef in half and form it into two thin patties slightly larger than the bun.\n4. Cook the patties in the hot pan over medium heat for 1 to 2 minutes on each side. Salt and pepper lightly.\n5. Build the burger in the following stacking order from the bottom up:\nbottom bun -> special sauce -> onions -> lettuce -> american cheese -> beef patty -> middle bun -> special sauce -> onion -> lettuce -> pickles -> beef patty -> top bun\n\nOptional if you want more than just thousand island dressing make the following sauce:\n1/2 cup mayonnaise\n2 tablespoons french dressing\n4 teaspoons sweet pickle relish\n1 tablespoon finely minced white onion\n1 teaspoon granulated sugar\n1/8 teaspoon salt',
    photo: 'big-mac.jpg',
>>>>>>> 297ff6dc0282d13858e84e41c74b1e91925e08a9
    createdAt: '2022-01-24T01:24:54.008Z',
    updatedAt: '2022-01-24T01:24:54.008Z',
    __v: 0,
  },
  {
    _id: '61ef2aa1baa9c6dd37fbc7a7',
    path: [],
    parent: null,
    ownerId: '61e608607f04825b4c4cd517',
    title: 'Homemade Chirashi Don',
    description:
      'I love Chirashi so much that I will legally make my middle name Chirashi. After this recipe, I will be known as Ivan Chirashi Don Tang. This recipe is for making sushi rice as the toppings can be anything you want!',
    ingredients: [
      {
        ingredient: 'Japanese short grain rice',
        amount: '2',
        unitOfMeasure: 'cups',
        _id: '61ef2aa1baa9c6dd37fbc7a8',
      },
      {
        ingredient: 'water',
        amount: '2',
        unitOfMeasure: 'cups',
        _id: '61ef2aa1baa9c6dd37fbc7a9',
      },
      {
        ingredient: 'unseasoned rice vinegar',
        amount: '1/4',
        unitOfMeasure: 'cup',
        _id: '61ef2aa1baa9c6dd37fbc7aa',
      },
      {
        ingredient: 'sugar',
        amount: '4',
        unitOfMeasure: 'tsp',
        _id: '61ef2aa1baa9c6dd37fbc7ab',
      },
      {
        ingredient: 'fine sea salt',
        amount: '1',
        unitOfMeasure: 'tsp',
        _id: '61ef2aa1baa9c6dd37fbc7ac',
      },
    ],
    instructions:
<<<<<<< HEAD
      'Sushi rice:\n\n*Note: Feel free to scale up the measurements for more rice!\n\n1. rinse the rice, place the rice in a fine-mesh strainer and give it a long rinse with cold water until the water runs clear.\n\n2.  cook the rice, easiest would be to use a rice cooker but an instant pot or stovetop will work as well.\n\n3. make sushi vinegar, while the rice is cooking heat the rice vinegar, sugar, and salt together in a small saucepan over medium-high heat until the mixture nearly simmers. Once it reaches this point remove it from the heat and whisk until the sugar has dissolved.\n\n4. Season the rice, once the rice is cooked transfer the rice to a large mixing bowl and evenly pour the sushi vinegar. Gently fold the rice with the vinegar until mixed evenly.\n\n5. Let the rice cool, cover the mixing bowl with a damp towel so that it is touching the surface of the rice to help prevent the rice from drying out. Let it cool until room temperature.\n\n6. Use it immediately or store it in an airtight food container for up to 3 days in a refrigerator.\n\nChirashi Don:\n\n1. Prepare the fish/toppings by slicing them into pieces or into bite-size pieces.\n\n2. Spoon however much rice you want into a bowl\n\n3. Place the prepared fish and toppings on top of the rice\n\n4. Enjoy!',
    photo: '',
=======
      'Sushi rice:\n*Note: Feel free to scale up the measurements for more rice!\n1. rinse the rice, place the rice in a fine-mesh strainer and give it a long rinse with cold water until the water runs clear.\n2.  cook the rice, easiest would be to use a rice cooker but an instant pot or stovetop will work as well.\n3. make sushi vinegar, while the rice is cooking heat the rice vinegar, sugar, and salt together in a small saucepan over medium-high heat until the mixture nearly simmers. Once it reaches this point remove it from the heat and whisk until the sugar has dissolved.\n4. Season the rice, once the rice is cooked transfer the rice to a large mixing bowl and evenly pour the sushi vinegar. Gently fold the rice with the vinegar until mixed evenly.\n5. Let the rice cool, cover the mixing bowl with a damp towel so that it is touching the surface of the rice to help prevent the rice from drying out. Let it cool until room temperature.\n6. Use it immediately or store it in an airtight food container for up to 3 days in a refrigerator.\nChirashi Don:\n1. Prepare the fish/toppings by slicing them into pieces or into bite-size pieces.\n2. Spoon however much rice you want into a bowl\n3. Place the prepared fish and toppings on top of the rice\n4. Enjoy!',
    photo: 'chirashi.jpg',
>>>>>>> 297ff6dc0282d13858e84e41c74b1e91925e08a9
    createdAt: '2022-01-24T22:39:29.650Z',
    updatedAt: '2022-01-24T22:39:29.650Z',
    __v: 0,
  },
  {
    _id: '61ef2bbabaa9c6dd37fbc7bd',
    path: ['61ef2aa1baa9c6dd37fbc7a7'],
    parent: '61ef2aa1baa9c6dd37fbc7a7',
    ownerId: '61e607f0311d699fd35f509e',
    title: 'Add kombu to the rice!',
    description:
      "I also love a good chirashi don but I thought it might give it a little extra flavor if you put in kombu when you're cooking the rice!",
    ingredients: [
      {
        ingredient: 'Japanese short grain rice',
        amount: '2',
        unitOfMeasure: 'cups',
        _id: '61ef2aa1baa9c6dd37fbc7a8',
      },
      {
        ingredient: 'water',
        amount: '2',
        unitOfMeasure: 'cups',
        _id: '61ef2aa1baa9c6dd37fbc7a9',
      },
      {
        ingredient: 'unseasoned rice vinegar',
        amount: '1/4',
        unitOfMeasure: 'cup',
        _id: '61ef2aa1baa9c6dd37fbc7aa',
      },
      {
        ingredient: 'sugar',
        amount: '4',
        unitOfMeasure: 'tsp',
        _id: '61ef2aa1baa9c6dd37fbc7ab',
      },
      {
        ingredient: 'fine sea salt',
        amount: '1',
        unitOfMeasure: 'tsp',
        _id: '61ef2aa1baa9c6dd37fbc7ac',
      },
      {
        ingredient: 'Kombu',
        amount: '4',
        unitOfMeasure: 'inch square',
        _id: '61ef2bbabaa9c6dd37fbc7c3',
      },
    ],
    instructions:
<<<<<<< HEAD
      'Sushi rice:\n\n*Note: Feel free to scale up the measurements for more rice!\n\n1. rinse the rice, place the rice in a fine-mesh strainer and give it a long rinse with cold water until the water runs clear.\n\n2.  cook the rice, easiest would be to use a rice cooker but an instant pot or stovetop will work as well. Put in the Kombu square with the rice and water into the rice cooker!\n\n3. make sushi vinegar, while the rice is cooking heat the rice vinegar, sugar, and salt together in a small saucepan over medium-high heat until the mixture nearly simmers. Once it reaches this point remove it from the heat and whisk until the sugar has dissolved.\n\n4. Season the rice, once the rice is cooked transfer the rice to a large mixing bowl and evenly pour the sushi vinegar. Gently fold the rice with the vinegar until mixed evenly.\n\n5. Let the rice cool, cover the mixing bowl with a damp towel so that it is touching the surface of the rice to help prevent the rice from drying out. Let it cool until room temperature.\n\n6. Use it immediately or store it in an airtight food container for up to 3 days in a refrigerator.\n\nChirashi Don:\n\n1. Prepare the fish/toppings by slicing them into pieces or into bite-size pieces.\n\n2. Spoon however much rice you want into a bowl\n\n3. Place the prepared fish and toppings on top of the rice\n\n4. Enjoy!',
    photo: '',
=======
      'Sushi rice:\n*Note: Feel free to scale up the measurements for more rice!\n1. rinse the rice, place the rice in a fine-mesh strainer and give it a long rinse with cold water until the water runs clear.\n2.  cook the rice, easiest would be to use a rice cooker but an instant pot or stovetop will work as well. Put in the Kombu square with the rice and water into the rice cooker!\n3. make sushi vinegar, while the rice is cooking heat the rice vinegar, sugar, and salt together in a small saucepan over medium-high heat until the mixture nearly simmers. Once it reaches this point remove it from the heat and whisk until the sugar has dissolved.\n4. Season the rice, once the rice is cooked transfer the rice to a large mixing bowl and evenly pour the sushi vinegar. Gently fold the rice with the vinegar until mixed evenly.\n5. Let the rice cool, cover the mixing bowl with a damp towel so that it is touching the surface of the rice to help prevent the rice from drying out. Let it cool until room temperature.\n6. Use it immediately or store it in an airtight food container for up to 3 days in a refrigerator.\nChirashi Don:\n1. Prepare the fish/toppings by slicing them into pieces or into bite-size pieces.\n2. Spoon however much rice you want into a bowl\n3. Place the prepared fish and toppings on top of the rice\n4. Enjoy!',
    photo: 'chirashi2.jpg',
>>>>>>> 297ff6dc0282d13858e84e41c74b1e91925e08a9
    createdAt: '2022-01-24T22:44:10.593Z',
    updatedAt: '2022-01-24T22:44:10.593Z',
    __v: 0,
  },
  {
    _id: '61ef658f2b99e9d451fbb529',
    path: [],
    parent: null,
    ownerId: '61ef64a8f892afce875f3810',
    title: 'Homemade Jam!',
    description: 'Jam Jam Jam!',
    ingredients: [
      {
        ingredient: 'fresh hulled strawberried',
        amount: '2',
        unitOfMeasure: 'lbs',
        _id: '61ef658f2b99e9d451fbb52a',
      },
      {
        ingredient: 'white sugar',
        amount: '4',
        unitOfMeasure: 'cups',
        _id: '61ef658f2b99e9d451fbb52b',
      },
      {
        ingredient: 'lemon juice',
        amount: '1/4',
        unitOfMeasure: 'cup',
        _id: '61ef658f2b99e9d451fbb52c',
      },
    ],
    instructions:
      "In a wide bowl, crush strawberries in batches until you have 4 cups of mashed berry. In a heavy-bottomed saucepan, mix together the strawberries, sugar, and lemon juice. Stir over low heat until the sugar is dissolved. Increase heat to high, and bring the mixture to a full rolling boil. Boil, stirring often, until the mixture reaches 220 degrees F (105 degrees C). Transfer to hot sterile jars, leaving 1/4 to 1/2 inch headspace, and seal. Process in a water bath. If the jam is going to be eaten right away, don't bother with processing, and just refrigerate.",
    photo: 'strawberry_jam.jpg',
    createdAt: '2022-01-25T02:50:55.914Z',
    updatedAt: '2022-01-25T02:50:55.914Z',
    __v: 0,
  },
  {
    _id: '61e6097228a24ac228581007',
    path: [],
    parent: null,
    ownerId: '61e608607f04825b4c4cd517',
    title: 'Eggy Omelettes',
    description: 'Simple and quick recipe for a moe moe omelette!',
    ingredients: [
      { ingredient: 'egg', amount: 5, unitOfMeasure: 'eggs' },
      { ingredient: 'butter', amount: 1, unitOfMeasure: 'cup' },
    ],
    instructions: 'Add butter to pan on low heat. Beat the eggs, and cook until done!!!',
    photo: 'omelette.jpg',
  },
  {
    _id: '61e6098028a24ac228581008',
    path: ['61e6097228a24ac228581007'],
    parent: '61e6097228a24ac228581007',
    ownerId: '61e607f0311d699fd35f509e',
    title: 'Eggy Weggy Omelettes',
    description: 'Simple and quick recipe for a moe moe omelette!',
    ingredients: [
      { ingredient: 'egg', amount: 10, unitOfMeasure: 'eggs' },
      { ingredient: 'butter', amount: 1, unitOfMeasure: 'cup' },
    ],
    instructions: 'Add butter to pan on low heat. Beat the eggs, and cook until done!!!',
    photo: 'omelette.jpg',
  },
  {
    _id: '61e6099628a24ac22858100a',
    path: ['61e6097228a24ac228581007'],
    parent: '61e6097228a24ac228581007',
    ownerId: '61e607f0311d699fd35f509e',
    title: 'Eggy Weggiest Omelettes',
    description: 'Simple and quick recipe for a moe moe omelette!',
    ingredients: [
      { ingredient: 'egg', amount: 6, unitOfMeasure: 'eggs' },
      { ingredient: 'butter', amount: 1, unitOfMeasure: 'cup' },
    ],
    instructions: 'Add butter to pan on low heat. Beat the eggs, and cook until done!!!',
    photo: 'omelette.jpg',
  },
  {
    _id: '61ef4c0abaa9c6dd37fbc8ea',
    path: [],
    parent: null,
    ownerId: '61e608607f04825b4c4cd517',
    title: 'Baked Portuguese Chicken Rice',
    description: 'Combines chicken, coconut curry, and fried rice in a baked dish!',
    ingredients: [
      {
        ingredient: 'cookedrice',
        amount: '6',
        unitOfMeasure: 'cups',
        _id: '61ef4c0abaa9c6dd37fbc8eb',
      },
      {
        ingredient: 'eggs',
        amount: '4',
        unitOfMeasure: '',
        _id: '61ef4c0abaa9c6dd37fbc8ec',
      },
      {
        ingredient: 'soy sauce',
        amount: '3',
        unitOfMeasure: 'tbsp',
        _id: '61ef4c0abaa9c6dd37fbc8ed',
      },
      {
        ingredient: 'cooking oil',
        amount: '3',
        unitOfMeasure: 'tbsp',
        _id: '61ef4c0abaa9c6dd37fbc8ee',
      },
      {
        ingredient: 'shaoxing cooking wine',
        amount: '1',
        unitOfMeasure: 'tsp',
        _id: '61ef4c0abaa9c6dd37fbc8ef',
      },
      {
        ingredient: 'salt',
        amount: '1 1/4',
        unitOfMeasure: 'tsp',
        _id: '61ef4c0abaa9c6dd37fbc8f0',
      },
      {
        ingredient: 'garlic powder',
        amount: '1/2',
        unitOfMeasure: 'tsp',
        _id: '61ef4c0abaa9c6dd37fbc8f1',
      },
      {
        ingredient: 'curry powder',
        amount: '1 1/2',
        unitOfMeasure: 'tsp',
        _id: '61ef4c0abaa9c6dd37fbc8f2',
      },
      {
        ingredient: 'onion diced',
        amount: '3/4',
        unitOfMeasure: 'cup',
        _id: '61ef4c0abaa9c6dd37fbc8f3',
      },
      {
        ingredient: 'potatoes diced',
        amount: '2',
        unitOfMeasure: 'cups',
        _id: '61ef4c0abaa9c6dd37fbc8f4',
      },
      {
        ingredient: 'canned coconut milk',
        amount: '400',
        unitOfMeasure: 'ml',
        _id: '61ef4c0abaa9c6dd37fbc8f5',
      },
      {
        ingredient: 'tumeric',
        amount: '1',
        unitOfMeasure: 'tsp',
        _id: '61ef4c0abaa9c6dd37fbc8f6',
      },
    ],
    instructions:
<<<<<<< HEAD
      '1. Slice chicken thighs in half. Marinate chicken in cooking wine, salt, garlic powder, curry powder. Marinade with 1 tsp cooking wine, 1/4 tsp salt, 1/2 tsp garlic powder and 1/2 tsp curry powder.\n\n2. Peel and dice potatoes. Then boil in hot water for 5 minutes until fork tender. Strain and set aside.\n\n3. In a large pan over medium-high heat, add 2 tbsp cooking oil and cooked rice. Break rice apart. Then add soy sauce and eggs. Mix everything together until eggs are cooked. Transfer the rice into a 9x13 baking dish and spread it out evenly.\n\n4. preheat oven to 500 degrees F.\n\n5. In the same cooking pan over high heat, add 1 tbsp cooking oil and diced onions. Followed by marinated chicken thighs. Brown chicken on each side for 5 minutes. Next add cooked potatoes, coconut milk, turmeric, curry powder, and salt. Mix well.\n\n6. Spoon chicken and sauce over fried rice and spread out evenly. Sprinkle cheese over top. Broil for 5-10 minutes until cheese has melted and browns slightly. Enjoy!',
    photo: '',
=======
      '1. Slice chicken thighs in half. Marinate chicken in cooking wine, salt, garlic powder, curry powder. Marinade with 1 tsp cooking wine, 1/4 tsp salt, 1/2 tsp garlic powder and 1/2 tsp curry powder.\n2. Peel and dice potatoes. Then boil in hot water for 5 minutes until fork tender. Strain and set aside.\n3. In a large pan over medium-high heat, add 2 tbsp cooking oil and cooked rice. Break rice apart. Then add soy sauce and eggs. Mix everything together until eggs are cooked. Transfer the rice into a 9x13 baking dish and spread it out evenly.\n4. preheat oven to 500 degrees F.\n5. In the same cooking pan over high heat, add 1 tbsp cooking oil and diced onions. Followed by marinated chicken thighs. Brown chicken on each side for 5 minutes. Next add cooked potatoes, coconut milk, turmeric, curry powder, and salt. Mix well.\n6. Spoon chicken and sauce over fried rice and spread out evenly. Sprinkle cheese over top. Broil for 5-10 minutes until cheese has melted and browns slightly. Enjoy!',
    photo: 'Baked-Portuguese-Chicken-Rice-3.jpg',
>>>>>>> 297ff6dc0282d13858e84e41c74b1e91925e08a9
    createdAt: '2022-01-25T01:02:02.425Z',
    updatedAt: '2022-01-25T01:02:02.425Z',
    __v: 0,
  },
  {
    _id: '61ef5bf0baa9c6dd37fbc98a',
    path: ['61ef4c0abaa9c6dd37fbc8ea'],
    parent: '61ef4c0abaa9c6dd37fbc8ea',
    ownerId: '61e607f0311d699fd35f509e',
    title: 'Spaghetti not Rice!',
    description:
      "This recipe can also be done with spaghetti! It's commonly done in Hong Kong style cafes!",
    ingredients: [
      {
        ingredient: 'spaghetti',
        amount: '4',
        unitOfMeasure: 'ounces',
        _id: '61ef4c0abaa9c6dd37fbc8eb',
      },
      {
        ingredient: 'shaoxing cooking wine',
        amount: '1',
        unitOfMeasure: 'tsp',
        _id: '61ef4c0abaa9c6dd37fbc8ef',
      },
      {
        ingredient: 'salt',
        amount: '1 1/4',
        unitOfMeasure: 'tsp',
        _id: '61ef4c0abaa9c6dd37fbc8f0',
      },
      {
        ingredient: 'garlic powder',
        amount: '1/2',
        unitOfMeasure: 'tsp',
        _id: '61ef4c0abaa9c6dd37fbc8f1',
      },
      {
        ingredient: 'curry powder',
        amount: '1 1/2',
        unitOfMeasure: 'tsp',
        _id: '61ef4c0abaa9c6dd37fbc8f2',
      },
      {
        ingredient: 'onion diced',
        amount: '3/4',
        unitOfMeasure: 'cup',
        _id: '61ef4c0abaa9c6dd37fbc8f3',
      },
      {
        ingredient: 'potatoes diced',
        amount: '2',
        unitOfMeasure: 'cups',
        _id: '61ef4c0abaa9c6dd37fbc8f4',
      },
      {
        ingredient: 'canned coconut milk',
        amount: '400',
        unitOfMeasure: 'ml',
        _id: '61ef4c0abaa9c6dd37fbc8f5',
      },
      {
        ingredient: 'tumeric',
        amount: '1',
        unitOfMeasure: 'tsp',
        _id: '61ef4c0abaa9c6dd37fbc8f6',
      },
      {
        ingredient: 'cooking oil',
        amount: '1',
        unitOfMeasure: 'tbsp',
        _id: '61ef5bf0baa9c6dd37fbc994',
      },
    ],
    instructions:
      '1. Slice chicken thighs in half. Marinate chicken in cooking wine, salt, garlic powder, curry powder. Marinade with 1 tsp cooking wine, 1/4 tsp salt, 1/2 tsp garlic powder and 1/2 tsp curry powder.\n\n2. Peel and dice potatoes. Then boil in hot water for 5 minutes until fork tender. Strain and set aside.\n\n3. Boil water in a saucepan and cook spaghetti. Transfer the spaghetti into a 9x13 baking dish and spread it out evenly.\n\n4. preheat oven to 500 degrees F.\n\n5. In the same cooking pan over high heat, add 1 tbsp cooking oil and diced onions. Followed by marinated chicken thighs. Brown chicken on each side for 5 minutes. Next add cooked potatoes, coconut milk, turmeric, curry powder, and salt. Mix well.\n\n6. Spoon chicken and sauce over fried rice and spread out evenly. Sprinkle cheese over top. Broil for 5-10 minutes until cheese has melted and browns slightly. Enjoy!',
    photo: '',
    createdAt: '2022-01-25T02:09:52.717Z',
    updatedAt: '2022-01-25T02:09:52.717Z',
    __v: 0,
  },
  {
    _id: '61ef5e3fbaa9c6dd37fbc9fb',
    path: ['61ef4c0abaa9c6dd37fbc8ea'],
    parent: '61ef4c0abaa9c6dd37fbc8ea',
    ownerId: '61e608607f04825b4c4cd517',
    title: 'Another Hong Kong Classic!',
    description:
      'Also a common Hong Kong cafe dish, you can change the sauce to a tomato-based sauce if you are not a fan of the coconut curry sauce! This dish has pork chops instead of chicken and a nice tangy tomato sauce instead of creamy coconut curry.',
    ingredients: [
      {
        ingredient: 'day old rice',
        amount: '6',
        unitOfMeasure: 'cups',
        _id: '61ef5e3fbaa9c6dd37fbc9fc',
      },
      {
        ingredient: 'eggs',
        amount: '4',
        unitOfMeasure: '',
        _id: '61ef5e3fbaa9c6dd37fbc9fd',
      },
      {
        ingredient: 'salt',
        amount: '1 1/2',
        unitOfMeasure: 'tsp',
        _id: '61ef5e3fbaa9c6dd37fbc9fe',
      },
      {
        ingredient: 'cooking oil',
        amount: '2',
        unitOfMeasure: 'tbsp',
        _id: '61ef5e3fbaa9c6dd37fbc9ff',
      },
      {
        ingredient: 'large tomatoes',
        amount: '4',
        unitOfMeasure: '',
        _id: '61ef5e3fbaa9c6dd37fbca00',
      },
      {
        ingredient: 'ketchup',
        amount: '6',
        unitOfMeasure: 'tbsp',
        _id: '61ef5e3fbaa9c6dd37fbca01',
      },
      {
        ingredient: 'worcestershire sauce',
        amount: '1',
        unitOfMeasure: 'tbsp',
        _id: '61ef5e3fbaa9c6dd37fbca02',
      },
      {
        ingredient: 'chicken stock',
        amount: '1/2',
        unitOfMeasure: 'cup',
        _id: '61ef5e3fbaa9c6dd37fbca03',
      },
      {
        ingredient: 'garlic',
        amount: '4',
        unitOfMeasure: 'cloves',
        _id: '61ef5e3fbaa9c6dd37fbca04',
      },
      {
        ingredient: 'large onion',
        amount: '1',
        unitOfMeasure: '',
        _id: '61ef5e3fbaa9c6dd37fbca05',
      },
      {
        ingredient: 'corn starch',
        amount: '1',
        unitOfMeasure: 'tbsp',
        _id: '61ef5e3fbaa9c6dd37fbca06',
      },
      {
        ingredient: 'sugar',
        amount: '1',
        unitOfMeasure: 'tbsp',
        _id: '61ef5e3fbaa9c6dd37fbca07',
      },
      {
        ingredient: 'ground black pepper',
        amount: '1',
        unitOfMeasure: 'tbso',
        _id: '61ef5e3fbaa9c6dd37fbca08',
      },
      {
        ingredient: 'grated mozzarella',
        amount: '250',
        unitOfMeasure: 'g',
        _id: '61ef5e3fbaa9c6dd37fbca09',
      },
      {
        ingredient: 'grated parmesan',
        amount: '1/3',
        unitOfMeasure: 'cup',
        _id: '61ef5e3fbaa9c6dd37fbca0a',
      },
    ],
    instructions:
      'Pork Chop\n\n1. Tenderize meat by pounding it with the back of a cleaver then marinate it in a mixture of Chinese wine, garlic, salt, freshly ground black pepper for at least 15 minutes.\n\n2. Place flour on a plate and beat eggs on another plate.\n\n3. Prepare a deep fryer and heat oil to 180C.\n\n4. Dip cutlet in egg and then in flour making sure it is coated well. Gently place each pork cutlet and cook until golden brown, once cooked transfer into a paper towel-lined wire rack.\n\nEgg Fried Rice\n\n1. Using a wok heat up the oil until it nearly reaches its smoking point.\n\n2. Add rice and salt and stir fry for a minute.\n\n3. Make a well in the middle of the wok then pour in beaten eggs, once cooked mix in together with the rice.\n\n4.  Remove from heat then set aside.\n\nTangy Tomato Sauce\n\n1. In a wok sauté the garlic and onions are in oil, once the onions turn transparent add the chopped tomatoes. Continue to sauté until tomatoes begin to soften.\n\n2. In a mixing bowl mix together tomato ketchup, salt, pepper, Worcestershire sauce, chicken stock, and cornstarch. Pour into the wok then simmer for 15 minutes.\n\nBaked Pork Chop and Rice\n\n1. Place fried rice in a large ovenproof dish or casserole\n\n2. Place fried pork chop on top of the rice.\n\n3. Pour the sauce on top of the pork chop.\n\n4. Add grated cheese on top of the sauce.\n\n5. Bake in a 220C preheated oven for 15-20 minutes or until the cheese it completely melted.',
    photo: '',
    createdAt: '2022-01-25T02:19:43.048Z',
    updatedAt: '2022-01-25T02:19:43.048Z',
    __v: 0,
  },
  {
    _id: '61ef5efabaa9c6dd37fbcb30',
    path: ['61ef4c0abaa9c6dd37fbc8ea', '61ef5e3fbaa9c6dd37fbc9fb'],
    parent: '61ef5e3fbaa9c6dd37fbc9fb',
    ownerId: '61e608607f04825b4c4cd517',
    title: 'Another Hong Kong Classic 2!',
    description: 'Can also be done with pasta!',
    ingredients: [
      {
        ingredient: 'salt',
        amount: '1 1/2',
        unitOfMeasure: 'tsp',
        _id: '61ef5e3fbaa9c6dd37fbc9fe',
      },
      {
        ingredient: 'large tomatoes',
        amount: '4',
        unitOfMeasure: '',
        _id: '61ef5e3fbaa9c6dd37fbca00',
      },
      {
        ingredient: 'ketchup',
        amount: '6',
        unitOfMeasure: 'tbsp',
        _id: '61ef5e3fbaa9c6dd37fbca01',
      },
      {
        ingredient: 'worcestershire sauce',
        amount: '1',
        unitOfMeasure: 'tbsp',
        _id: '61ef5e3fbaa9c6dd37fbca02',
      },
      {
        ingredient: 'chicken stock',
        amount: '1/2',
        unitOfMeasure: 'cup',
        _id: '61ef5e3fbaa9c6dd37fbca03',
      },
      {
        ingredient: 'garlic',
        amount: '4',
        unitOfMeasure: 'cloves',
        _id: '61ef5e3fbaa9c6dd37fbca04',
      },
      {
        ingredient: 'large onion',
        amount: '1',
        unitOfMeasure: '',
        _id: '61ef5e3fbaa9c6dd37fbca05',
      },
      {
        ingredient: 'corn starch',
        amount: '1',
        unitOfMeasure: 'tbsp',
        _id: '61ef5e3fbaa9c6dd37fbca06',
      },
      {
        ingredient: 'sugar',
        amount: '1',
        unitOfMeasure: 'tbsp',
        _id: '61ef5e3fbaa9c6dd37fbca07',
      },
      {
        ingredient: 'ground black pepper',
        amount: '1',
        unitOfMeasure: 'tbso',
        _id: '61ef5e3fbaa9c6dd37fbca08',
      },
      {
        ingredient: 'grated mozzarella',
        amount: '250',
        unitOfMeasure: 'g',
        _id: '61ef5e3fbaa9c6dd37fbca09',
      },
      {
        ingredient: 'grated parmesan',
        amount: '1/3',
        unitOfMeasure: 'cup',
        _id: '61ef5e3fbaa9c6dd37fbca0a',
      },
      {
        ingredient: 'spaghetti',
        amount: '4',
        unitOfMeasure: 'ounces',
        _id: '61ef5efabaa9c6dd37fbcb3d',
      },
    ],
    instructions:
      'Pork Chop\n\n1. Tenderize meat by pounding it with the back of a cleaver then marinate it in a mixture of Chinese wine, garlic, salt, freshly ground black pepper for at least 15 minutes.\n\n2. Place flour on a plate and beat eggs on another plate.\n\n3. Prepare a deep fryer and heat oil to 180C.\n\n4. Dip cutlet in egg and then in flour making sure it is coated well. Gently place each pork cutlet and cook until golden brown, once cooked transfer into a paper towel-lined wire rack.\n\nSpaghetti\n\n1. Cook the spaghetti in a saucepan of boiling water\n\nTangy Tomato Sauce\n\n1. In a wok sauté the garlic and onions are in oil, once the onions turn transparent add the chopped tomatoes. Continue to sauté until tomatoes begin to soften.\n\n2. In a mixing bowl mix together tomato ketchup, salt, pepper, Worcestershire sauce, chicken stock, and cornstarch. Pour into the wok then simmer for 15 minutes.\n\nBaked Pork Chop and Rice\n\n1. Place spaghetti in a large ovenproof dish or casserole\n\n2. Place fried pork chop on top of the spaghetti.\n\n3. Pour the sauce on top of the pork chop.\n\n4. Add grated cheese on top of the sauce.\n\n5. Bake in a 220C preheated oven for 15-20 minutes or until the cheese is completely melted.',
    photo: '',
    createdAt: '2022-01-25T02:22:50.656Z',
    updatedAt: '2022-01-25T02:22:50.656Z',
    __v: 0,
  },
  {
    _id: '61e607f0311d699fd35f509e',
    path: [],
    parent: null,
    ownerId: '61e607f0311d699fd35f509e',
    title: 'Creamy Alfredo Sauce',
    description: 'Simple and quick recipe for a 5 minute alfredo sauce. Great with pasta!',
    ingredients: [
      { ingredient: 'heavy cream', amount: 100, unitOfMeasure: 'ml' },
      { ingredient: 'butter', amount: 0.25, unitOfMeasure: 'cups' },
    ],
    instructions:
      'Put butter into a small sauce pan on a medium to low flame. Once the butter has melted pour in the heavy cream and allow to simmer. Gently stir to avoid over boiling.',
    photo: 'alfredo.jpg',
  },
  {
    _id: '61e608607f04825b4c4cd517',
    path: ['61e607f0311d699fd35f509e'],
    parent: '61e607f0311d699fd35f509e',
    ownerId: '61e607f0311d699fd35f509e',
    title: 'Add Pepper',
    description:
      'Building on the previous fork, I decided to add an ungodly amount of pepper to the sauce.',
    ingredients: [
      { ingredient: 'heavy cream', amount: 100, unitOfMeasure: 'ml' },
      { ingredient: 'butter', amount: 0.25, unitOfMeasure: 'cups' },
      { ingredient: 'fine ground black pepper', amount: 4, unitOfMeasure: 'table spoons' },
    ],
    instructions:
      'Put butter into a small sauce pan on a medium to low flame. Once the butter has melted pour in the heavy cream and allow to simmer. Gently stir to avoid over boiling. Add the black pepper to the sauce and stir well to evenly distribute the pepper in the sauce',
    photo: 'alfredo.jpg',
  },

  {
    _id: '61e608961e6098028a24ac22',
    path: ['61e607f0311d699fd35f509e', '61e608607f04825b4c4cd517'],
    parent: '61e608607f04825b4c4cd517',
    ownerId: '61e607f0311d699fd35f509e',
    title: 'Too much pepper and not enough garlic :(',
    description:
      'Reducing the amount of pepper in the sauce and adding minced/chopped garlic to the sauce!',
    ingredients: [
      { ingredient: 'heavy cream', amount: 100, unitOfMeasure: 'ml' },
      { ingredient: 'butter', amount: 0.25, unitOfMeasure: 'cups' },
      { ingredient: 'fine ground black pepper', amount: 1.5, unitOfMeasure: 'table spoons' },
      { ingredient: 'garlic', amount: 3, unitOfMeasure: 'cloves' },
    ],
    instructions:
      'Finely chop or mince garlic cloves. Put butter into a small sauce pan on a medium to low flame. Once the butter has melted add the garlic and leave until fragrent. Once the garlic is fragrent, pour in the heavy cream and allow to simmer. Gently stir to avoid over boiling. Add the black pepper to the sauce and stir well to evenly distribute the pepper in the sauce',
    photo: 'alfredo.jpg',
  },
  {
    _id: '61e60945bda713dc8a3f7427',
    path: ['61e607f0311d699fd35f509e', '61e608607f04825b4c4cd517'],
    parent: '61e608607f04825b4c4cd517',
    ownerId: '61e608607f04825b4c4cd517',
    title: 'My Family Recipe',
    description:
      "This is the recipe my asian grandmother used to make for us. This technically makes no sense because I doubt she would make a alfredo sauce but hey I don't make the rules.",
    ingredients: [
      { ingredient: 'heavy cream', amount: 100, unitOfMeasure: 'ml' },
      { ingredient: 'butter', amount: 0.25, unitOfMeasure: 'cups' },
      { ingredient: 'fine ground black pepper', amount: 1.5, unitOfMeasure: 'table spoons' },
      { ingredient: 'garlic', amount: 3, unitOfMeasure: 'cloves' },
      { ingredient: 'grated parmesan cheese', amount: 0.75, unitOfMeasure: 'cups' },
    ],
    instructions:
      "Finely chop or mince garlic cloves. Put butter into a small sauce pan on a medium to low flame. Once the butter has melted add the garlic and leave until fragrent. Once the garlic is fragrent, pour in the heavy cream and allow to simmer. Gently stir to avoid over boiling. Add the black pepper to the sauce and stir well to evenly distribute the pepper in the sauce. Finally add the cheese into the sauce and stir until melted. Don't forget to save some for garnish!",
    photo: 'alfredo.jpg',
  },

  {
    _id: '61ede159b4e6d9f28ae80bf4',
    path: [],
    parent: null,
    ownerId: '61e607f0311d699fd35f509e',
    title: 'Hot Chocolate in 7 Minutes!',
    description: 'I make nice hot chocolate for Christmas :)',
    ingredients: [
      {
        ingredient: 'unsweetened cocoa powder',
        amount: '1/3',
        unitOfMeasure: 'cup',
        _id: '61ede159b4e6d9f28ae80bf5',
      },
      {
        ingredient: 'white sugar',
        amount: '3/4',
        unitOfMeasure: 'cup',
        _id: '61ede159b4e6d9f28ae80bf6',
      },
      {
        ingredient: 'salt',
        amount: '1',
        unitOfMeasure: 'pinch',
        _id: '61ede159b4e6d9f28ae80bf7',
      },
      {
        ingredient: 'boiling water',
        amount: '1/3',
        unitOfMeasure: 'cup',
        _id: '61ede159b4e6d9f28ae80bf8',
      },
      {
        ingredient: 'milk',
        amount: '3.5',
        unitOfMeasure: 'cups',
        _id: '61ede159b4e6d9f28ae80bf9',
      },
      {
        ingredient: 'vanilla extract',
        amount: '3/4',
        unitOfMeasure: 'teaspoon',
        _id: '61ede159b4e6d9f28ae80bfa',
      },
      {
        ingredient: 'half and half cream',
        amount: '1/2',
        unitOfMeasure: 'cup',
        _id: '61ede159b4e6d9f28ae80bfb',
      },
    ],
    instructions:
      "Combine the cocoa, sugar and pinch of salt in a saucepan. Blend in the boiling water. Bring this mixture to an easy boil while you stir. Simmer and stir for about 2 minutes. Watch that it doesn't scorch. Stir in 3 1/2 cups of milk and heat until very hot, but do not boil! Remove from heat and add vanilla. Divide between 4 mugs. Add the cream to the mugs of cocoa to cool it to drinking temperature.",
    photo: 'hot-chocolate.jpg',
    createdAt: '2022-01-23T23:14:33.759Z',
    updatedAt: '2022-01-23T23:14:33.759Z',
    __v: 0,
  },
  {
    _id: '61ef0c1b771f83a3b41f7629',
    path: [],
    parent: null,
    ownerId: '61e608607f04825b4c4cd517',
    title: 'Slow Cooker Brisket',
    description:
      "This recipe serves approximately 8 people. I wanted to replicate a brisket from a good old fashion smoker but I didn't have the space so I thought to try a slow cooker and here are the results!",
    ingredients: [
      {
        ingredient: 'Beef brisket',
        amount: '1.5-2',
        unitOfMeasure: 'kg',
        _id: '61ef0c1b771f83a3b41f762a',
      },
      {
        ingredient: 'olive oil',
        amount: '1',
        unitOfMeasure: 'tbsp',
        _id: '61ef0c1b771f83a3b41f762b',
      },
      {
        ingredient: 'brown sugar',
        amount: '110',
        unitOfMeasure: 'g',
        _id: '61ef0c1b771f83a3b41f762c',
      },
      {
        ingredient: 'paprika powder',
        amount: '2',
        unitOfMeasure: 'tsp',
        _id: '61ef0c1b771f83a3b41f762d',
      },
      {
        ingredient: 'onion powder',
        amount: '3',
        unitOfMeasure: 'tsp',
        _id: '61ef0c1b771f83a3b41f762e',
      },
      {
        ingredient: 'garlic powder',
        amount: '1',
        unitOfMeasure: 'tsp',
        _id: '61ef0c1b771f83a3b41f762f',
      },
      {
        ingredient: 'cumin powder',
        amount: '0.5',
        unitOfMeasure: 'tsp',
        _id: '61ef0c1b771f83a3b41f7630',
      },
      {
        ingredient: 'mustard powder',
        amount: '3',
        unitOfMeasure: 'tsp',
        _id: '61ef0c1b771f83a3b41f7631',
      },
      {
        ingredient: 'salt',
        amount: '1',
        unitOfMeasure: 'tsp',
        _id: '61ef0c1b771f83a3b41f7632',
      },
      {
        ingredient: 'black pepper',
        amount: '3',
        unitOfMeasure: 'tsp',
        _id: '61ef0c1b771f83a3b41f7633',
      },
      {
        ingredient: 'garlic',
        amount: '4',
        unitOfMeasure: 'cloves',
        _id: '61ef0c1b771f83a3b41f7634',
      },
      {
        ingredient: 'apple cider vinegar',
        amount: '125',
        unitOfMeasure: 'ml',
        _id: '61ef0c1b771f83a3b41f7635',
      },
      {
        ingredient: 'ketchup',
        amount: '375',
        unitOfMeasure: 'ml',
        _id: '61ef0c1b771f83a3b41f7636',
      },
      {
        ingredient: 'cayenne pepper',
        amount: '1',
        unitOfMeasure: 'tsp',
        _id: '61ef0c1b771f83a3b41f7637',
      },
      {
        ingredient: 'worcestershire sauce',
        amount: '1',
        unitOfMeasure: 'tbsp',
        _id: '61ef0c1b771f83a3b41f7638',
      },
    ],
    instructions:
<<<<<<< HEAD
      '1. Mix the 1tbsp of brown sugar,  paprika, 1 tsp of onion powder, garlic powder, cumin, 1 tsp of mustard powder, 1 tsp of salt, and 1 tsp black pepper to create the rub.\n\nRub the seasoning rub onto the brisket and if you have time leave it for at least 30 minutes and up to 24 hours in the fridge.\n\n2. Put the rest of the minced garlic, apple cider vinegar, ketchup, brown sugar, black pepper, onion powder, mustard powder, cayenne pepper, and Worcestershire sauce into the slow cooker. Mix well and then place the brisket into the slow cooker, feel free to squish it in.\n\n3. Cook for 8 (1.5kg/3lbs) - 10 hours (2kg/4lbs).\n\n4. Once done remove brisket onto a tray.\n\n5. Pour the leftover liquid into a saucepan, simmer over medium-high heat and reduce until it thickens to a syrup consistency.\n\n6. Meanwhile, drizzle brisket with oil then roast in a 200C/390F oven for 15 minutes until brown spots appear. Remove then baste generously with sauce, then return to oven for 5 minutes. Remove and baste again, then return to oven for 5 - 10 minutes until it caramelizes.\n\n7. Enjoy the brisket sliced thinly across the grain!',
    photo: '',
=======
      '1. Mix the 1tbsp of brown sugar,  paprika, 1 tsp of onion powder, garlic powder, cumin, 1 tsp of mustard powder, 1 tsp of salt, and 1 tsp black pepper to create the rub.\nRub the seasoning rub onto the brisket and if you have time leave it for at least 30 minutes and up to 24 hours in the fridge.\n2. Put the rest of the minced garlic, apple cider vinegar, ketchup, brown sugar, black pepper, onion powder, mustard powder, cayenne pepper, and Worcestershire sauce into the slow cooker. Mix well and then place the brisket into the slow cooker, feel free to squish it in.\n3. Cook for 8 (1.5kg/3lbs) - 10 hours (2kg/4lbs).\n4. Once done remove brisket onto a tray.\n5. Pour the leftover liquid into a saucepan, simmer over medium-high heat and reduce until it thickens to a syrup consistency.\n6. Meanwhile, drizzle brisket with oil then roast in a 200C/390F oven for 15 minutes until brown spots appear. Remove then baste generously with sauce, then return to oven for 5 minutes. Remove and baste again, then return to oven for 5 - 10 minutes until it caramelizes.\n7. Enjoy the brisket sliced thinly across the grain!',
    photo: 'brisket.jpg',
>>>>>>> 297ff6dc0282d13858e84e41c74b1e91925e08a9
    createdAt: '2022-01-24T20:29:15.447Z',
    updatedAt: '2022-01-24T20:29:15.447Z',
    __v: 0,
  },
  {
    _id: '61ef138cbaa9c6dd37fbc557',
    path: ['61ef0c1b771f83a3b41f7629'],
    parent: '61ef0c1b771f83a3b41f7629',
    ownerId: '61e607f0311d699fd35f509e',
    title: 'Oven Brisket',
    description: 'Here is an oven alternative that I use!',
    ingredients: [
      {
        ingredient: 'garlic',
        amount: '4',
        unitOfMeasure: 'large cloves',
        _id: '61ef138cbaa9c6dd37fbc558',
      },
      {
        ingredient: 'kosher salt',
        amount: '1/2',
        unitOfMeasure: 'tsp',
        _id: '61ef138cbaa9c6dd37fbc559',
      },
      {
        ingredient: 'rosemary',
        amount: '4',
        unitOfMeasure: 'sprigs',
        _id: '61ef138cbaa9c6dd37fbc55a',
      },
      {
        ingredient: 'extra-virgin olive oil',
        amount: '1/4',
        unitOfMeasure: 'cup',
        _id: '61ef138cbaa9c6dd37fbc55b',
      },
      {
        ingredient: 'beef brisket',
        amount: '4',
        unitOfMeasure: 'lbs',
        _id: '61ef138cbaa9c6dd37fbc55c',
      },
      {
        ingredient: 'carrots',
        amount: '4',
        unitOfMeasure: '',
        _id: '61ef138cbaa9c6dd37fbc55d',
      },
      {
        ingredient: 'celery',
        amount: '3',
        unitOfMeasure: 'stalks',
        _id: '61ef138cbaa9c6dd37fbc55e',
      },
      {
        ingredient: 'red onions',
        amount: '4',
        unitOfMeasure: '',
        _id: '61ef138cbaa9c6dd37fbc55f',
      },
      {
        ingredient: 'dry red wine',
        amount: '2',
        unitOfMeasure: 'cup',
        _id: '61ef138cbaa9c6dd37fbc560',
      },
      {
        ingredient: 'can of whole tomatoes',
        amount: '16',
        unitOfMeasure: 'ounces',
        _id: '61ef138cbaa9c6dd37fbc561',
      },
      {
        ingredient: 'fresh flat-leaf parsely',
        amount: '1',
        unitOfMeasure: 'handful',
        _id: '61ef138cbaa9c6dd37fbc562',
      },
      {
        ingredient: 'bay leaves',
        amount: '3',
        unitOfMeasure: '',
        _id: '61ef138cbaa9c6dd37fbc563',
      },
      {
        ingredient: 'all-purpose flour',
        amount: '1',
        unitOfMeasure: 'tbsp',
        _id: '61ef138cbaa9c6dd37fbc564',
      },
    ],
    instructions:
<<<<<<< HEAD
      '1. Preheat the oven to 325 degrees F.\n\n2. On a cutting board, mash the garlic and 1/2 teaspoon of the salt together with the flat-side of a knife into a paste. Add the rosemary and continue to mash until incorporated. Put the garlic-rosemary paste in a small bowl and add 2 tablespoons of olive oil; stir to combine. \n\n3. Season both sides of the brisket with a fair amount of kosher salt and ground black pepper. Place a large roasting pan or Dutch oven over medium-high flame and coat with the remaining olive oil. Put the brisket in the roasting pan and sear to form a nice brown crust on both sides. Lay the vegetables all around the brisket and pour the rosemary paste over the whole thing. Add the wine and tomatoes; toss in the parsley and bay leaves. Cover the pan tightly with aluminum foil and transfer to the oven. Bake for about 3 to 4 hours, basting every 30 minutes with the pan juices until the beef is fork-tender. \n\n4. Remove the brisket to a cutting board and let it rest for 15 minutes. Scoop the vegetables out of the roasting pan and onto a platter, cover to keep warm. Pour out some of the excess fat, and put the roasting pan with the pan juices on the stove over medium-high heat. Boil and stir for 5 minutes until the sauce is reduced by 1/2. (If you want a thicker sauce, mix 1 tablespoon of flour with 2 tablespoons of wine or water and blend into the gravy). \n\n5. Slice the brisket across the grain (the muscle lines) at a slight diagonal and serve!',
    photo: '',
=======
      '1. Preheat the oven to 325 degrees F.\n2. On a cutting board, mash the garlic and 1/2 teaspoon of the salt together with the flat-side of a knife into a paste. Add the rosemary and continue to mash until incorporated. Put the garlic-rosemary paste in a small bowl and add 2 tablespoons of olive oil; stir to combine. \n3. Season both sides of the brisket with a fair amount of kosher salt and ground black pepper. Place a large roasting pan or Dutch oven over medium-high flame and coat with the remaining olive oil. Put the brisket in the roasting pan and sear to form a nice brown crust on both sides. Lay the vegetables all around the brisket and pour the rosemary paste over the whole thing. Add the wine and tomatoes; toss in the parsley and bay leaves. Cover the pan tightly with aluminum foil and transfer to the oven. Bake for about 3 to 4 hours, basting every 30 minutes with the pan juices until the beef is fork-tender. \n4. Remove the brisket to a cutting board and let it rest for 15 minutes. Scoop the vegetables out of the roasting pan and onto a platter, cover to keep warm. Pour out some of the excess fat, and put the roasting pan with the pan juices on the stove over medium-high heat. Boil and stir for 5 minutes until the sauce is reduced by 1/2. (If you want a thicker sauce, mix 1 tablespoon of flour with 2 tablespoons of wine or water and blend into the gravy). \n5. Slice the brisket across the grain (the muscle lines) at a slight diagonal and serve!',
    photo: 'brisket.jpg',
>>>>>>> 297ff6dc0282d13858e84e41c74b1e91925e08a9
    createdAt: '2022-01-24T21:01:00.967Z',
    updatedAt: '2022-01-24T21:01:00.967Z',
    __v: 0,
  },
  {
    _id: '61ef1528baa9c6dd37fbc5e1',
    path: ['61ef0c1b771f83a3b41f7629', '61ef138cbaa9c6dd37fbc557'],
    parent: '61ef138cbaa9c6dd37fbc557',
    ownerId: '61e607f0311d699fd35f509e',
    title: 'Oven Brisket v2',
    description: 'I developed an easier oven made brisket!',
    ingredients: [
      {
        ingredient: 'beef brisket',
        amount: '3',
        unitOfMeasure: 'lbs',
        _id: '61ef1528baa9c6dd37fbc5e2',
      },
      {
        ingredient: 'medium onion',
        amount: '1',
        unitOfMeasure: '',
        _id: '61ef1528baa9c6dd37fbc5e3',
      },
      {
        ingredient: 'beer',
        amount: '12',
        unitOfMeasure: 'fluid ounce',
        _id: '61ef1528baa9c6dd37fbc5e4',
      },
      {
        ingredient: 'tomato based chili sauce',
        amount: '12',
        unitOfMeasure: 'ounce',
        _id: '61ef1528baa9c6dd37fbc5e5',
      },
      {
        ingredient: 'packed brown sugar',
        amount: '3/4',
        unitOfMeasure: 'cup',
        _id: '61ef1528baa9c6dd37fbc5e6',
      },
    ],
    instructions:
<<<<<<< HEAD
      '1. Preheat the oven to 325 degrees F (165 degrees C).\n\n2. Season the brisket on all sides with salt and pepper, and place in a glass baking dish. Cover with a layer of sliced onions. In a medium bowl, mix together the beer, chili sauce, and brown sugar. Pour over the roast. Cover the dish tightly with aluminum foil.\n\n3. Bake for 3 hours in the preheated oven. Remove the aluminum foil, and bake for an additional 30 minutes. Let the brisket rest and cool slightly before slicing and returning to the dish. Reheat in the oven with the sauce spooned over the sliced meat.',
    photo: '',
=======
      '1. Preheat the oven to 325 degrees F (165 degrees C).\n2. Season the brisket on all sides with salt and pepper, and place in a glass baking dish. Cover with a layer of sliced onions. In a medium bowl, mix together the beer, chili sauce, and brown sugar. Pour over the roast. Cover the dish tightly with aluminum foil.\n3. Bake for 3 hours in the preheated oven. Remove the aluminum foil, and bake for an additional 30 minutes. Let the brisket rest and cool slightly before slicing and returning to the dish. Reheat in the oven with the sauce spooned over the sliced meat.',
    photo: 'brisket.jpg',
>>>>>>> 297ff6dc0282d13858e84e41c74b1e91925e08a9
    createdAt: '2022-01-24T21:07:52.870Z',
    updatedAt: '2022-01-24T21:07:52.870Z',
    __v: 0,
  },
  {
    _id: '61ef182fbaa9c6dd37fbc66c',
    path: ['61ef0c1b771f83a3b41f7629'],
    parent: '61ef0c1b771f83a3b41f7629',
    ownerId: '61e608607f04825b4c4cd517',
    title: 'Slow Cooker Brisket v2',
    description: 'I redeveloped and simplified my recipe :)',
    ingredients: [
      {
        ingredient: 'smoked paprika',
        amount: '3',
        unitOfMeasure: 'tbsp',
        _id: '61ef182fbaa9c6dd37fbc66d',
      },
      {
        ingredient: 'ground black pepper',
        amount: '2',
        unitOfMeasure: 'tbsp',
        _id: '61ef182fbaa9c6dd37fbc66e',
      },
      {
        ingredient: 'kosher salt',
        amount: '2',
        unitOfMeasure: 'tbsp',
        _id: '61ef182fbaa9c6dd37fbc66f',
      },
      {
        ingredient: 'brown sugar',
        amount: '1',
        unitOfMeasure: 'tbsp',
        _id: '61ef182fbaa9c6dd37fbc670',
      },
      {
        ingredient: 'chili powder',
        amount: '1',
        unitOfMeasure: 'tbsp',
        _id: '61ef182fbaa9c6dd37fbc671',
      },
      {
        ingredient: 'ground cumin',
        amount: '1',
        unitOfMeasure: 'tsp',
        _id: '61ef182fbaa9c6dd37fbc672',
      },
      {
        ingredient: 'beef brisket',
        amount: '.5',
        unitOfMeasure: 'lbs',
        _id: '61ef182fbaa9c6dd37fbc673',
      },
      {
        ingredient: 'bbq sauce',
        amount: '3/4',
        unitOfMeasure: 'cup',
        _id: '61ef182fbaa9c6dd37fbc674',
      },
      {
        ingredient: 'water (optional)',
        amount: '1/4',
        unitOfMeasure: 'cup',
        _id: '61ef182fbaa9c6dd37fbc675',
      },
      {
        ingredient: 'worcestershire sauce',
        amount: '1',
        unitOfMeasure: 'tbsp',
        _id: '61ef182fbaa9c6dd37fbc676',
      },
      {
        ingredient: 'liquid smoke',
        amount: '1/4',
        unitOfMeasure: 'tsp',
        _id: '61ef182fbaa9c6dd37fbc677',
      },
      {
        ingredient: 'onion',
        amount: '1/2',
        unitOfMeasure: '',
        _id: '61ef182fbaa9c6dd37fbc678',
      },
    ],
    instructions:
<<<<<<< HEAD
      '1. Mix paprika, pepper, salt, brown sugar, chili powder, and cumin together in a bowl; rub evenly over the surface of the brisket. Put brisket in a large, resealable plastic bag; refrigerate 30 minutes to overnight.\n\n2. Stir barbeque sauce, water, Worcestershire sauce, and liquid smoke together in the bottom of a slow cooker. Lay brisket into the sauce mixture. Arrange onions atop the brisket.\n\n3. Cook on Low until brisket is very tender, 6 to 7 hours. Rest brisket 10 minutes before slicing or shredding; serve with sauce from the slow cooker.',
    photo: '',
=======
      '1. Mix paprika, pepper, salt, brown sugar, chili powder, and cumin together in a bowl; rub evenly over the surface of the brisket. Put brisket in a large, resealable plastic bag; refrigerate 30 minutes to overnight.\n2. Stir barbeque sauce, water, Worcestershire sauce, and liquid smoke together in the bottom of a slow cooker. Lay brisket into the sauce mixture. Arrange onions atop the brisket.\n3. Cook on Low until brisket is very tender, 6 to 7 hours. Rest brisket 10 minutes before slicing or shredding; serve with sauce from the slow cooker.',
    photo: 'brisket.jpg',
>>>>>>> 297ff6dc0282d13858e84e41c74b1e91925e08a9
    createdAt: '2022-01-24T21:20:47.725Z',
    updatedAt: '2022-01-24T21:20:47.725Z',
    __v: 0,
  },
];
